[package]
name = "stac-async"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
path-slash = "0.1"
reqwest = "0.11"
serde_json = "1"
stac = { git = "https://github.com/gadomski/stac-rs", version = "0.0.4" }
tokio = { version = "1.17", features = ["fs", "macros"] }
url = "2"
